FROM openjdk:8-alpine

ENV GRADLE_OPTS "-Dorg.gradle.daemon=false"
ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

RUN apk --no-cache add bash libstdc++

ADD build.gradle $APP_HOME
ADD settings.gradle $APP_HOME
ADD gradlew $APP_HOME
ADD gradle $APP_HOME/gradle

ADD src $APP_HOME/src
RUN $APP_HOME/gradlew clean build -x test
